### PR TITLE
fix registries is http generate cert.d file name err

### PR DESCRIPTION
**Pull request by NatureLR**
## Description

when containerRuntime.containerd.registries addr is http then generate cert.d file name err

## Related Issue

https://github.com/dragonflyoss/Dragonfly2/issues/2527

### CODE REVIEW

**Comment by gaius-qi** [comment]
You should update `Chart.yaml` version:
1. https://github.com/dragonflyoss/helm-charts/blob/main/charts/dragonfly/Chart.yaml#L6
2. https://github.com/dragonflyoss/helm-charts/blob/main/charts/dragonfly/Chart.yaml#L7

Add changelog to `Chart.yaml`:
https://github.com/dragonflyoss/helm-charts/blob/main/charts/dragonfly/Chart.yaml#L28

**Comment by NatureLR** [comment]
> @NatureLR
> 
> You should update `Chart.yaml` version:
> 
> 1. https://github.com/dragonflyoss/helm-charts/blob/main/charts/dragonfly/Chart.yaml#L6
> 2. https://github.com/dragonflyoss/helm-charts/blob/main/charts/dragonfly/Chart.yaml#L7
> 
> Add changelog to `Chart.yaml`: https://github.com/dragonflyoss/helm-charts/blob/main/charts/dragonfly/Chart.yaml#L28

done

**Comment by hyy0322** [comment]
@NatureLR DCO is required

**Comment by NatureLR** [comment]
> @NatureLR DCO is required

looks like it's done

**Review by gaius-qi — APPROVED** [review]
LGTM

**Pull request merged**
