### PR TITLE
Patch pull request #73 - config.toml

### PR DESCRIPTION
**Pull request by czomo**
Signed-off-by: czomo <tomaszjdul@gmail.com>
I've made a mistake(my bad) in https://github.com/dragonflyoss/helm-charts/pull/73 and config doesn't work the way we need. I modified it to be able to fetch the values  from values.yaml. Right now it always stays the same - the default one `config.toml`.

### CODE REVIEW

**Comment by gaius-qi** [comment]
> /assign @gaius-qi

Thx, please fix the conflicting.

**Comment by czomo** [comment]
@gaius-qi Fix that, take a look please

**Review by gaius-qi — APPROVED** [review]
LGTM

**Pull request merged**
